#!/usr/bin/bash

# Add color support for common commands
alias ls="ls --color"
alias grep="grep --color"
alias egrep="egrep --color"
alias fgrep="fgrep --color"

# cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# ls
alias lsa="ls -A"
alias lsl="ls -l"
alias lsla="ls -lA"
alias lslah="ls -lAh"

# git
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gph="git push"
alias gpl="git pull"
alias gf="git fetch"
alias gd="git diff"
alias gl="git log"

# tar & gzip
alias mktarball="tar -czvf"
alias untarball="tar -zxvf"

# use bat over cat
if alias_or_cmd bat; then
  alias cat="bat"
elif alias_or_cmd batcat; then
  # debian renames binary to "batcat". See https://github.com/sharkdp/bat/issues/2455
  alias cat="batcat"
fi

# use eza over ls
if alias_or_cmd eza; then
  alias ls="eza"
fi

# use "python" alias for "python3" if and only if not already used
if ! alias_or_cmd python && alias_or_cmd python3; then
  alias python="python3"
fi
# use "py" alias for "python" if and only if not already used
if ! alias_or_cmd py && alias_or_cmd python; then
  alias py="python"
fi
